<title>Async/Await syntax</title>

<main id="timer"></main>

<script id="Setup">

    const timer = document.querySelector("main#timer");
    const interval = setInterval(() => {
        const d = new Date()
        timer.textContent = d.toLocaleTimeString() + ":" + d.getMilliseconds();
    }, 100);
    


    const getPromisedValue = (value, ms = 2_000, throwRate = 0.15) => {
        return new Promise((resolve, reject) => {
            const shouldThrow = Math.random() <= throwRate;
            setTimeout(() => shouldThrow ? reject("Bad Luck!") : resolve(value), ms);
        });
    };

</script>

<script id="Asynchronous callbacks - callback hell">

    // getPromisedValue(42)
    //     .then(console.log)
    //     .catch(console.error)
    //     .finally(() => console.log("Finito!"));



    // getPromisedValue(42)
    //     .then(x => getPromisedValue(Math.random())
    //         .then(y => console.log(x + y))
    //     ).catch(_ => console.log("We had an error"))
    //     .finally(_ => console.log("Finitooo"));

</script>

<script id="Async/Await - Writing asynchronous code the synchronous way">

    // async function processSomethingAsync() {
    //     const x = await getPromisedValue(42);
    //     const y = await getPromisedValue(Math.random());
    //     console.log(x + y);
    // }


    // async function processSomethingAsync() {
    //     console.log(await getPromisedValue(42) + await getPromisedValue(Math.random()));
    // }


    // const processSomethingAsync = async function() {
    //     console.log(await getPromisedValue(42) + await getPromisedValue(Math.random()));
    // };


    // const processSomethingAsync = async () => {
    //     console.log(await getPromisedValue(42) + await getPromisedValue(Math.random()));
    // };


    // processSomethingAsync();


    // processSomethingAsync().then(() => console.log("Finito"));

</script>

<script id="Async functions">

    // const getAnswer = async () => {
    //     return 42;
    // };

    // console.log(getAnswer());

    // getAnswer().then(answer => console.log(answer));
    // getAnswer().then(console.log);

    // (async () => {
    //     const answer = await getAnswer();
    //     console.log(answer);
    // })();



    /* Inlining async operations & mixing async/await + callbacks */
    // (async () => {
    //     const users = await (await fetch("https://jsonplaceholder.typicode.com/users")).json();
    //     console.log(users);

    //     console.log(await (await fetch("https://jsonplaceholder.typicode.com/users")).json());

    //     console.log(await fetch("https://jsonplaceholder.typicode.com/users").then(r => r.json()));
    // })();



    /* Callbacks VS Async/Await */
    // const volume = (a, b, h) => a * b * h;

    // const calcVolumeCallbacks = () => {
    //     const a = getPromisedValue(42, 1_000, 0);
    //     const b = getPromisedValue(21, 3_000, 0);
    //     const h = getPromisedValue(69, 500, 0);

    //     getPromisedValue(42, 1_000, 0).then(a => {
    //         getPromisedValue(21, 3_000, 0).then(b => {
    //             getPromisedValue(69, 500, 0).then(h => {
    //                 const v = volume(a, b, h);
    //                 console.log({ a, b, h, v });
    //             });
    //         });
    //     });
    // };

    // const calcVolumeAsyncAwait = async () => {
    //     const a = await getPromisedValue(42, 1_000, 0);
    //     const b = await getPromisedValue(21, 3_000, 0);
    //     const h = await getPromisedValue(69, 500, 0);

    //     const v = volume(a, b, h);
    //     console.log({ a, b, h, v });
    // };

    // calcVolumeCallbacks();
    // calcVolumeAsyncAwait();

</script>

<script id="Catching errors">

    // const processSomethingAsync = async () => {
    //     try {
    //         // const x = await getPromisedValue(42, 2_000, 0.5);
    //         // const y = await getPromisedValue(Math.random(), 3_000, 0.5);
    //         // const x = await getPromisedValue(42, 2_000, 1).catch(console.error);
    //         // const y = await getPromisedValue(Math.random(), 3_000, 1).catch(console.error);
    //         const x = await getPromisedValue(42, 2_000, 1).catch(_ => 1);
    //         const y = await getPromisedValue(Math.random(), 3_000, 1).catch(_ => 2);
    //         console.log(x + y);
    //     } catch (error) {
    //         console.log("We had an error");
    //     } finally {
    //         console.log("Finitooo");
    //     }
    // };

    // processSomethingAsync()
    //     .then(_ => console.log("Chip chipi chapa chapa"))
    //     .finally(_ => console.log("Dubi dubi"));



    /* Rethrowing error & not handling it + Async errors */
    // const uncaughtProcessSomethingAsync = async () => {
    //     try {
    //         throw new Error("Dupa");
    //         const x = await getPromisedValue(42, 2_000, 0);
    //         const y = await getPromisedValue(Math.random(), 3_000, 1);
    //         console.log(x + y);
    //     } catch (error) {
    //         throw error;
    //     }
    // };

    // try {
    //     uncaughtProcessSomethingAsync()
    //         .then(_ => console.log("Chip chipi chapa chapa"))
    //         .finally(_ => console.log("Dubi dubi"))
    //         // .catch(_ => console.log("Oooops"))
    // } catch (error) {
    //     console.log("There was an error but we've dealt with it ;)");
    // }



    /* Handling Errors and custom errors */
    class UserNotFoundError extends Error {
        constructor() {
            super("User not found!");
        }

        toString() {
            return "404 - No user LMAO";
        }
    }

    const getUser = () => {
        if (Math.random() > 0.5) {
            if (Math.random() > 0.5) throw new Error("404");
            else throw new UserNotFoundError();
        }

        return fetch("https://jsonplaceholder.typicode.com/users/1").then(r => r.json());
    };

    (async () => {
        try {
            const user = await getUser();
            console.log(`Displaying user profile page: ${user.name}`, user);
        } catch (error) {
            if (error instanceof UserNotFoundError) {
                console.log(`User not found! Displaying 404 page.`);
            } else {
                console.error(error);
                throw error;
            }
        }
    })();


</script>
